### ISSUE TITLE
install problems on pi zero / raspbian

### ISSUE THREAD

**Issue by unddef** [nielsnl68/node-red-contrib-i2c#10]
Hello,

first of all thank you for your work.
Im using your node on a rasperry pi 1b(rasbian)

 without problems.
Now im trying to install the node on a raspberry pi zero. 
I did the following so far:
-installed new Rasbian lite system from https://www.raspberrypi.org/downloads/raspbian/
-installed node-red from raspbian repository (Version: 0.15.3)
-tried to install node-red-contrib-i2c by the described command (npm install —unsafe-perm node-red-contrib-i2c) [by the way: there is a typo on http://flows.nodered.org/node/node-red-contrib-i2c : in the codeblock there are no double - in front of unsafe-perm. so you cant copy and paste]

while installing i get a ton of errors while compiling the node. the error log from console is included in the txtfile i attached. also i included the npm-debug.log.

[error-log-i2c.txt](https://github.com/nielsnl68/node-contrib-i2c/files/925313/error-log-i2c.txt)
[npm-debug-log.txt](https://github.com/nielsnl68/node-contrib-i2c/files/925314/npm-debug-log.txt)

I suspect a problem with a missing library. But i have no idea how to tackle the problem.
Maybe you can help me 

With best regards
Christian

**Comment by nielsnl68** [comment]
Thanks for your kind words.

The current version works only for the 4.x version of node.js.



Op 17 apr. 2017 11:57 schreef "unddef" <notifications@github.com>:

**Comment by unddef** [comment]
Hello,

thank you for the tip.
For anyone running in the same problems:

dont install node-red by using apt-get. apparently the version from the rasbian repository is old.
instead use the install instructions provided here https://nodered.org/docs/hardware/raspberrypi

it uses an install script from the internet 
bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)

**Comment by unddef** [comment]
To follow up my documentation:

i used the posted link and (accidentally) installed node.js v6 (6.10.2 to be precisely)
My findings: the scan and also the read node are working so far.
the set (output) node is not working. It appears that there is a functioncall to a function that doesnt exist.
Copy of Debug: "TypeError: String.isString is not a function"

I know, you told me it is working only with v4 so i will try this tomorrow (found nvm to switch versions).
Are you generally interested in updating you library? I can try to help but my programming skills a limited (yet). 
But certainly im able to do some testing. 

Greetings

**Comment by unddef** [comment]
sry for spaming, but i think i found the problem.
in the file 26-i2c.js in line 107
else if ((typeof payload === "string") || Array.isArray(payload))
Array.isArray is a deprecated function (https://nodejs.org/api/util.html#util_util_isarray_object)

maybe this might work: 
else if ((typeof payload === "string") || (payload instanceof Array))
got the idea here http://stackoverflow.com/questions/5941706/javascript-detect-if-argument-is-array-instead-of-object-node-js
this should solve the problem, cause the function is not long afterwards. 
but then there is my next problem: i have no idea how i can change the code and test it.
I have to recompile the node, right?

**Comment by nielsnl68** [comment]
This should now be fixed, because I have upgrade my node modules. please check of your issue still exist.
