### ISSUE TITLE
installing with npm installs old source codes

### ISSUE THREAD

**Issue by hilschernetpi** [nielsnl68/node-red-contrib-i2c#11]
Hi Niels,

I installed i2c node using "npm install —unsafe-perm node-red-contrib-i2c" on my Raspberry. Installation goes well.
But what I can see is that the latest edits of source code 26-i2c.js are not part of the installation. Especially checking the payload if its of type string with 'String.isString(payload)' (old) and 'typeof payload === "string"' (new).
Exactly this check (old) makes me problems now cause I want to send msg.payload as an array but this check rejects it

**Comment by nielsnl68** [comment]
it should now be fixed.
Because I have upgrade my node modules. please check of your issue still exist.
