### ISSUE TITLE
msg.command

### ISSUE THREAD

**Issue by selfus** [nielsnl68/node-red-contrib-i2c#15]
Hello,

I am trying to use this library, and I am not able to find anything related to msg.command.

What values can this variable get? What does each value means?

Any help apreciated, thanks

**Comment by nielsnl68** [comment]
the msg.command would be a byte (0..255)

**Comment by selfus** [comment]
@nielsnl68 But what does each byte means? That is what I am wondering.

Thanks for your reply.

**Comment by nielsnl68** [comment]
That depends on the device you connect to the i2c bus.

Op 16 okt. 2017 18:30 schreef "selfus" <notifications@github.com>:

**Comment by wglm13** [comment]
I am using a HD44780U LCD wich msg.command I need to use / where I can finde the commands?

**Comment by Zoolu74** [comment]
I'm also looking for any information on this. Can there be an example?

**Comment by prairietech** [comment]
I too am looking for further explanation of the Command field. Could you please provide further information?

**Comment by agenteDserrano** [comment]
My device not accept command on get. Need only address like this> i2cget -y 1 0x40

**Comment by Willi66** [comment]
Is it possible that an empty command get no error! A PCF8574 or PCF8575 needs no command just the adress and sends on "read" the state of the I/Os and on "write" condition it sets the I/Os with the following Byte!

**Comment by mlwalter77** [comment]
Is it possible to use commands of 2 bytes (16-bit)?  I have a Sensirion SPS30, which I can see when using the I2C Scan node.  However, the command to read data is 0x0300 and I am looking to pull in 60 bytes of data.  From what I can tell the node accepts only 8-bit command.

**Comment by Barabba11** [comment]
Hi, I don't see reasons too to send a command to the I2C device on read operations, and as I see it doesn't really send it.. I think you just took the same "template" for output and that's why it still the command available. Can you please remove it? Thank you

**Comment by nielsnl68** [comment]
requesting data without a command should now fixed thanks to @exlicite.

On how the command function works is different between devices. you need to read the devices manual to figure out how it works. sorry
