### ISSUE TITLE
How can I read a byte without writing anything?

### ISSUE THREAD

**Issue by DeviousPenguin** [nielsnl68/node-red-contrib-i2c#19]
Hello, is there a was I can read a byte over the i2c bus using this node?

I need something that does something like this:

```
$ i2cget -y 1 0x20 
0xff
````

I tried leaving the command option blank in nodered but i get message saying 'command value is missing'

Thanks

**Comment by Barabba11** [comment]
seems it doesn't send anything in read mode, so I thin they just have to remove this command option

**Comment by nielsnl68** [comment]
thanks to @exlicite this issue should now been fixed.
