### ISSUE TITLE
Could not install /home/pi/.node-red/—unsafe-perm

### ISSUE THREAD

**Issue by madhujiot** [nielsnl68/node-red-contrib-i2c#2]
hi, I've RPI 3 model B and trying to add the node-contrib-i2c as I need to hook a I2C sensor asynchronously. Got the below error. Please revert with a suggestion/fix, thanks.

pi@raspberrypi:~/.node-red $ npm install —unsafe-perm node-red-contrib-i2c
npm ERR! addLocal Could not install /home/pi/.node-red/—unsafe-perm
npm ERR! Linux 4.4.34-v7+
npm ERR! argv "node" "/usr/local/bin/npm" "install" "—unsafe-perm" "node-red-contrib-i2c"
npm ERR! node v0.10.29
npm ERR! npm  v2.15.11
npm ERR! path /home/pi/.node-red/—unsafe-perm
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open '/home/pi/.node-red/—unsafe-perm'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log
pi@raspberrypi:~/.node-red $

**Comment by nielsnl68** [comment]
Can you try without the --unsafe_perm option?


Op 28 jan. 2017 23:53 schreef "madhujiot" <notifications@github.com>:

**Comment by madhujiot** [comment]
hi, even I tried without -unsafe_perm option. Got the same/similar error with the build as per below. Please let me know if anything missed, thx.

pi@raspberrypi:~ $ npm install node-red-contrib-i2c
/
> i2c@0.2.3 install /home/pi/node_modules/node-red-contrib-i2c/node_modules/i2c
> node-gyp rebuild

make: Entering directory '/home/pi/node_modules/node-red-contrib-i2c/node_modules/i2c/build'
  CXX(target) Release/obj.target/i2c/src/i2c.o
../src/i2c.cc: In function ‘void setAddress(int8_t)’:
../src/i2c.cc:24:14: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
     isolate->ThrowException(
              ^
../src/i2c.cc: In function ‘void Scan(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:48:49: error: call of overloaded ‘New(v8::Local<v8::Primitive>)’ is ambiguous
   Local<Value> err = Nan::New<Value>(Nan::Null());
                                                 ^
../src/i2c.cc:48:49: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:193:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_implementation_pre_12_inl.h:245:21: note: v8::Local<T> Nan::New(v8::Handle<T>) [with T = v8::Value]
 inline v8::Local<T> New(v8::Handle<T> h) {
                     ^
../node_modules/nan/nan_implementation_pre_12_inl.h:260:21: note: v8::Local<T> Nan::New(const Nan::Global<S>&) [with T = v8::Value]
 inline v8::Local<T> New(Global<T> const& p) {
                     ^
../src/i2c.cc: In function ‘void Open(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:85:49: error: call of overloaded ‘New(v8::Local<v8::Primitive>)’ is ambiguous
   Local<Value> err = Nan::New<Value>(Nan::Null());
                                                 ^
../src/i2c.cc:85:49: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:193:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_implementation_pre_12_inl.h:245:21: note: v8::Local<T> Nan::New(v8::Handle<T>) [with T = v8::Value]
 inline v8::Local<T> New(v8::Handle<T> h) {
                     ^
../node_modules/nan/nan_implementation_pre_12_inl.h:260:21: note: v8::Local<T> Nan::New(const Nan::Global<S>&) [with T = v8::Value]
 inline v8::Local<T> New(Global<T> const& p) {
                     ^
../src/i2c.cc: In function ‘void Read(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:108:49: error: call of overloaded ‘New(v8::Local<v8::Primitive>)’ is ambiguous
   Local<Value> err = Nan::New<Value>(Nan::Null());
                                                 ^
../src/i2c.cc:108:49: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:193:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_implementation_pre_12_inl.h:245:21: note: v8::Local<T> Nan::New(v8::Handle<T>) [with T = v8::Value]
 inline v8::Local<T> New(v8::Handle<T> h) {
                     ^
../node_modules/nan/nan_implementation_pre_12_inl.h:260:21: note: v8::Local<T> Nan::New(const Nan::Global<S>&) [with T = v8::Value]
 inline v8::Local<T> New(Global<T> const& p) {
                     ^
../src/i2c.cc: In function ‘void ReadByte(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:131:49: error: call of overloaded ‘New(v8::Local<v8::Primitive>)’ is ambiguous
   Local<Value> err = Nan::New<Value>(Nan::Null());
                                                 ^
../src/i2c.cc:131:49: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:193:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_implementation_pre_12_inl.h:245:21: note: v8::Local<T> Nan::New(v8::Handle<T>) [with T = v8::Value]
 inline v8::Local<T> New(v8::Handle<T> h) {
                     ^
../node_modules/nan/nan_implementation_pre_12_inl.h:260:21: note: v8::Local<T> Nan::New(const Nan::Global<S>&) [with T = v8::Value]
 inline v8::Local<T> New(Global<T> const& p) {
                     ^
../src/i2c.cc: In function ‘void ReadBlock(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:157:49: error: call of overloaded ‘New(v8::Local<v8::Primitive>)’ is ambiguous
   Local<Value> err = Nan::New<Value>(Nan::Null());
                                                 ^
../src/i2c.cc:157:49: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:193:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_implementation_pre_12_inl.h:245:21: note: v8::Local<T> Nan::New(v8::Handle<T>) [with T = v8::Value]
 inline v8::Local<T> New(v8::Handle<T> h) {
                     ^
../node_modules/nan/nan_implementation_pre_12_inl.h:260:21: note: v8::Local<T> Nan::New(const Nan::Global<S>&) [with T = v8::Value]
 inline v8::Local<T> New(Global<T> const& p) {
                     ^
../src/i2c.cc: In function ‘void Write(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:196:49: error: call of overloaded ‘New(v8::Local<v8::Primitive>)’ is ambiguous
   Local<Value> err = Nan::New<Value>(Nan::Null());
                                                 ^
../src/i2c.cc:196:49: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:193:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_implementation_pre_12_inl.h:245:21: note: v8::Local<T> Nan::New(v8::Handle<T>) [with T = v8::Value]
 inline v8::Local<T> New(v8::Handle<T> h) {
                     ^
../node_modules/nan/nan_implementation_pre_12_inl.h:260:21: note: v8::Local<T> Nan::New(const Nan::Global<S>&) [with T = v8::Value]
 inline v8::Local<T> New(Global<T> const& p) {
                     ^
../src/i2c.cc: In function ‘void WriteByte(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:214:49: error: call of overloaded ‘New(v8::Local<v8::Primitive>)’ is ambiguous
   Local<Value> err = Nan::New<Value>(Nan::Null());
                                                 ^
../src/i2c.cc:214:49: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:193:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_implementation_pre_12_inl.h:245:21: note: v8::Local<T> Nan::New(v8::Handle<T>) [with T = v8::Value]
 inline v8::Local<T> New(v8::Handle<T> h) {
                     ^
../node_modules/nan/nan_implementation_pre_12_inl.h:260:21: note: v8::Local<T> Nan::New(const Nan::Global<S>&) [with T = v8::Value]
 inline v8::Local<T> New(Global<T> const& p) {
                     ^
../src/i2c.cc: In function ‘void WriteBlock(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:236:49: error: call of overloaded ‘New(v8::Local<v8::Primitive>)’ is ambiguous
   Local<Value> err = Nan::New<Value>(Nan::Null());
                                                 ^
../src/i2c.cc:236:49: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:193:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_implementation_pre_12_inl.h:245:21: note: v8::Local<T> Nan::New(v8::Handle<T>) [with T = v8::Value]
 inline v8::Local<T> New(v8::Handle<T> h) {
                     ^
../node_modules/nan/nan_implementation_pre_12_inl.h:260:21: note: v8::Local<T> Nan::New(const Nan::Global<S>&) [with T = v8::Value]
 inline v8::Local<T> New(Global<T> const& p) {
                     ^
../src/i2c.cc: In function ‘void WriteWord(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:256:49: error: call of overloaded ‘New(v8::Local<v8::Primitive>)’ is ambiguous
   Local<Value> err = Nan::New<Value>(Nan::Null());
                                                 ^
../src/i2c.cc:256:49: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:193:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_implementation_pre_12_inl.h:245:21: note: v8::Local<T> Nan::New(v8::Handle<T>) [with T = v8::Value]
 inline v8::Local<T> New(v8::Handle<T> h) {
                     ^
../node_modules/nan/nan_implementation_pre_12_inl.h:260:21: note: v8::Local<T> Nan::New(const Nan::Global<S>&) [with T = v8::Value]
 inline v8::Local<T> New(Global<T> const& p) {
                     ^
i2c.target.mk:92: recipe for target 'Release/obj.target/i2c/src/i2c.o' failed
make: *** [Release/obj.target/i2c/src/i2c.o] Error 1
make: Leaving directory '/home/pi/node_modules/node-red-contrib-i2c/node_modules/i2c/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.34-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/node-red-contrib-i2c/node_modules/i2c
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 4.4.34-v7+
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-red-contrib-i2c"
npm ERR! node v0.10.29
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! i2c@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i2c@0.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the i2c package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs i2c
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls i2c
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
pi@raspberrypi:~ $ pwd
/home/pi
pi@raspberrypi:~ $ ls
Desktop    Downloads  Music          Pictures  python_games  templog.db
Documents  get_temp   npm-debug.log  Public    Templates     Videos
pi@raspberrypi:~ $ cd ~./node-red
-bash: cd: ~./node-red: No such file or directory
pi@raspberrypi:~ $ cd ~./nodered
-bash: cd: ~./nodered: No such file or directory
pi@raspberrypi:~ $ cd ~/.node-red
pi@raspberrypi:~/.node-red $ ls
flows_raspberrypi_cred.json  lib           npm-debug.log
flows_raspberrypi.json       node_modules  settings.js
pi@raspberrypi:~/.node-red $ npm install node-red-contrib-i2c
npm ERR! Linux 4.4.34-v7+
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-red-contrib-i2c"
npm ERR! node v0.10.29
npm ERR! npm  v2.15.11
npm ERR! path /home/pi/.node-red/node_modules/node-red-contrib-i2c/node_modules/i2c/node_modules/.bin/cake
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, unlink '/home/pi/.node-red/node_modules/node-red-contrib-i2c/node_modules/i2c/node_modules/.bin/cake'
npm ERR!  { [Error: EACCES, unlink '/home/pi/.node-red/node_modules/node-red-contrib-i2c/node_modules/i2c/node_modules/.bin/cake']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/pi/.node-red/node_modules/node-red-contrib-i2c/node_modules/i2c/node_modules/.bin/cake' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/home/pi/.node-red/node_modules/node-red-contrib-i2c/node_modules/i2c/node_modules/.bin/cake'
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/pi/.node-red/node_modules/node-red-contrib-i2c/node_modules/i2c/node_modules/.bin/cake']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/pi/.node-red/node_modules/node-red-contrib-i2c/node_modules/i2c/node_modules/.bin/cake' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log
pi@raspberrypi:~/.node-red $

**Comment by nielsnl68** [comment]
I am not totally sure of this is the issue or not.

But i do not support node.js 0.10.x please upgrade to the newest version of
node.js an node_red.js and try  to install again.



Op 31 jan. 2017 14:15 schreef "madhujiot" <notifications@github.com>:

**Comment by madhujiot** [comment]
Yes, I re-installed again the new version and installed node-contrib-i2c through the palette settings in node-red directly. No error this time, thanks for your suggestion.
I've started using the I2C controls, partially succeeded. If you have any samples of block/burst read application please share, that will help.
Thank you.
