### ISSUE TITLE
Read PCF8574

### ISSUE THREAD

**Issue by exlicite** [nielsnl68/node-red-contrib-i2c#20]
Hi,

When you read data on PCF8574 or PCF8574A, no command should be send.

Please find code update to permit read data without command.

Best regards,

Stéphane

[26-i2c.js.txt](https://github.com/nielsnl68/node-red-contrib-i2c/files/2715577/26-i2c.js.txt)

**Comment by nielsnl68** [comment]
I have merge your code today. thanks
