### ISSUE TITLE
Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by tjohnson10010** [nielsnl68/node-red-contrib-i2c#3]
Hi, 
This is similar to the other issue except I've all ready tried your suggestion of dropping the "unsafe..." command.  I've used in /.nod-red directory the command: npm install node-red-contrib-i2c  (Log attached with errors highlighted in yellow...line 53, line 493, lines 647-651, and several starting at line 660).  Since I have updated with the latest version of Rasbian, I used the Palette to install the node which also fails. I've seen some clues to this problem even suggesting updating node.js binaries but so far that is not productive.  I hope you have some suggestions as I really need the i2c node as my sensor is a smart sensor and sends text data.  Looking forward to implementing your nodes in my design.

[Node Red  Log 17-01-30.docx](https://github.com/nielsnl68/node-contrib-i2c/files/740160/Node.Red.Log.17-01-30.docx

Regards,
Tim Johnson

**Comment by nielsnl68** [comment]
I2c uses Nodejs 4.x

**Comment by tjohnson10010** [comment]
Thank you for the reply.  I'm going over to flows.nodered.org and ask them a few questions...like why does their search function pull us nodes that don't work on their software.  Or is that a Github issue?Tim Johnson-----Original Message-----
