### ISSUE TITLE
 Error: Invalid I2C bus number false

### ISSUE THREAD

**Issue by jkarsten** [nielsnl68/node-red-contrib-i2c#37]
Hello,

i updated my node to 0.7.4 and now i have an Error " Error: Invalid I2C bus number false"
Oh its on an RPi3
I tried an fresh install with Buster an Node-RED v1.2.6 Node.js v12.20.0,
I installed only node-red-contrib-i2c and have still the same error.
sudo i2cdetect -y 1 show me all my devices on the bus.
In the node-red forum is a second User from today. https://discourse.nodered.org/t/node-red-contribi2c-sht31/37056

Thank you,
Jörg

**Comment by dceejay** [comment]
Version 0.7.5 now published.

**Comment by jkarsten** [comment]
Thank you. Works very nice.

**Comment by SonoraTechnical** [comment]
0.7.5 works for me as well... fixed the bus num error. thank you dceejay!

**Comment by stonehippo** [comment]
Ugh, had a typo in my repo that wasn't on my test systems (missed a commit, it seems). Sorry about that @dceejay and thanks for getting to the fix before I could.
