### ISSUE TITLE
Instalation error DietPi

### ISSUE THREAD

**Issue by jemarr** [nielsnl68/node-red-contrib-i2c#48]
Hi.

I've installed your node one year ago in a NanoPi Neo with DietPi and was running like a charm....

Now I want to install again with latest DietPi and Node-Red versions and I got a lot of errors doing exactly the same procedure:

96 verbose pkgid i2c-bus@5.2.3
97 verbose cwd /mnt/dietpi_userdata/node-red
98 verbose Linux 6.1.53-current-sunxi
99 verbose node v21.0.0
100 verbose npm  v10.2.1
101 error code 1
102 error path /mnt/dietpi_userdata/node-red/node_modules/i2c-bus
103 error command failed
104 error command sh -c node-gyp rebuild
105 error gyp info it worked if it ends with ok
105 error gyp info using node-gyp@9.4.0
105 error gyp info using node@21.0.0 | linux | arm
105 error gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
105 error gyp info spawn /usr/bin/python3
105 error gyp info spawn args [
105 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
105 error gyp info spawn args   'binding.gyp',
105 error gyp info spawn args   '-f',
105 error gyp info spawn args   'make',
105 error gyp info spawn args   '-I',
105 error gyp info spawn args   '/mnt/dietpi_userdata/node-red/node_modules/i2c-bus/build/config.gypi',
105 error gyp info spawn args   '-I',
105 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
105 error gyp info spawn args   '-I',
105 error gyp info spawn args   '/mnt/dietpi_userdata/node-red/.cache/node-gyp/21.0.0/include/node/common.gypi',
105 error gyp info spawn args   '-Dlibrary=shared_library',
105 error gyp info spawn args   '-Dvisibility=default',
105 error gyp info spawn args   '-Dnode_root_dir=/mnt/dietpi_userdata/node-red/.cache/node-gyp/21.0.0',
105 error gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
105 error gyp info spawn args   '-Dnode_lib_file=/mnt/dietpi_userdata/node-red/.cache/node-gyp/21.0.0/<(target_arch)/node.lib',
105 error gyp info spawn args   '-Dmodule_root_dir=/mnt/dietpi_userdata/node-red/node_modules/i2c-bus',
105 error gyp info spawn args   '-Dnode_engine=v8',
105 error gyp info spawn args   '--depth=.',
105 error gyp info spawn args   '--no-parallel',
105 error gyp info spawn args   '--generator-output',
105 error gyp info spawn args   'build',
105 error gyp info spawn args   '-Goutput_dir=.'
105 error gyp info spawn args ]
105 error gyp ERR! build error
105 error gyp ERR! stack Error: not found: make
105 error gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:10:17)
105 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:57:18
105 error gyp ERR! stack     at new Promise (<anonymous>)
105 error gyp ERR! stack     at step (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:54:21)
105 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:71:22
105 error gyp ERR! stack     at new Promise (<anonymous>)
105 error gyp ERR! stack     at subStep (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:69:33)
105 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:80:22
105 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
105 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
105 error gyp ERR! System Linux 6.1.53-current-sunxi
105 error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
105 error gyp ERR! cwd /mnt/dietpi_userdata/node-red/node_modules/i2c-bus
105 error gyp ERR! node -v v21.0.0
105 error gyp ERR! node-gyp -v v9.4.0
105 error gyp ERR! not ok
106 verbose exit 1

**Comment by jemarr** [comment]
I always enter as root user, so full access

**Comment by jemarr** [comment]
this is not the complete log, just when errors appear.

**Comment by jemarr** [comment]
i2c-tools are installed ok

**Comment by dceejay** [comment]
You don't have the build-essential tools package installed. Also we don't support non-LTS versions of nodejs so ideally stick to node18

**Comment by jemarr** [comment]
Installed (apt install build-essential) and working fine.

Thanks

I've Node.js v21.0.0 and NPM V10.2.0 installed, as default in last Dietpi distro.

I can't remember if I installed manually build essential package last year on my first NanoPi Neo or it is already done by default in Dietpi older versions,

Do you know ?

Thanks again !!!

**Comment by dceejay** [comment]
I don't use Diet-Pi so have no idea how it has changed over time. Good luck.
