### ISSUE TITLE
Error when installing node-red-contrib-i2c on raspberry pi b

### ISSUE THREAD

**Issue by Toshibass** [nielsnl68/node-red-contrib-i2c#6]
I get following when trying to install ..... any ideas ?

pi@raspberrypi:~/.node-red $ npm install node-red-contrib-i2c

> i2c@0.2.3 install /home/pi/.node-red/node_modules/i2c
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python2 -c import platform; print(platform.python_version());
gyp ERR! stack Traceback (most recent call last):
gyp ERR! stack   File "/usr/lib/python2.7/site.py", line 68, in <module>
gyp ERR! stack     import os
gyp ERR! stack   File "/usr/lib/python2.7/os.py", line 400, in <module>
gyp ERR! stack     import UserDict
gyp ERR! stack   File "/usr/lib/python2.7/UserDict.py", line 83, in <module>
gyp ERR! stack     import _abcoll
gyp ERR! stack   File "/usr/lib/python2.7/_abcoll.py", line 11, in <module>
gyp ERR! stack     from abc import ABCMeta, abstractmethod
gyp ERR! stack   File "/usr/lib/python2.7/abc.py", line 8, in <module>
gyp ERR! stack     from _weakrefset import WeakSet
gyp ERR! stack ValueError: bad marshal data (unknown type code)
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:206:12)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Linux 4.4.48+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/i2c
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/.node-red/package.json'
npm WARN .node-red No description
npm WARN .node-red No repository field.
npm WARN .node-red No README data
npm WARN .node-red No license field.
npm ERR! Linux 4.4.48+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-i2c"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! i2c@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i2c@0.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the i2c package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs i2c
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls i2c
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log

**Comment by nielsnl68** [comment]
Try using node.js 4.2 as suggested by node-red.

Op 13 mrt. 2017 19:12 schreef "Toshibass" <notifications@github.com>:
