### ISSUE TITLE
msg.command and isString

### ISSUE THREAD

**Issue by peteshew** [nielsnl68/node-red-contrib-i2c#8]
I came across a couple of issues when starting to use it. There is an error in the code thta should allow the use of msg.command. It correctly detects the provided command but actually uses the null value  from the configuration.  (node.command instead of msg.command)

I also had an issue with String.isString not being found - I replaced the test with typeof payload === 'string' and it works OK.

**Comment by peteshew** [comment]
Apologies, I see you have corrected the command issue

**Comment by nielsnl68** [comment]
Yes, but does it fix your other issue of .isString () ?

Op 28 mrt. 2017 10:42 schreef "peteshew" <notifications@github.com>:

**Comment by peteshew** [comment]
No, I am assuming that since it totally failed until I changed it that it must be a problem with my setup. Otherwise, it would be an issue for most people. I tried updating node.js to 6.10.1 and node-red to 0.16.2 but that didn't help.

**Comment by nielsnl68** [comment]
For now i only support 4.x try that one.

Op 28 mrt. 2017 11:59 schreef "peteshew" <notifications@github.com>:

**Comment by peteshew** [comment]
I was on 4.? and upgraded to try and solve the isString and another problem.  I'll leave my modified test in for now as it is working OK. Thanks.

**Comment by nielsnl68** [comment]
Can you create a pull request for the change you made then i put it in the code as well

**Comment by peteshew** [comment]
The problem with that is that I would have to learn about GIT. One day I might have to bite the bullet, but my learning curve is limited these days and moving from PHP, Python, etc to node.js and node-red is taking most of my time.
 /String.isString(payload)/typeof payload === "string"/ should do it.

**Comment by BakedInd** [comment]
I am a bit new to all of this, please bare with me :)

The isString error you were talking about.. is just:   "TypeError: String.isString is not a function" ?

I am getting that as well. I am trying to use an Atlas Scientific EZO Conductivity monitor and I need to send it "R" to get a single reading.

But when I place that in the payload... I get the isString error.

If I place an INT in the payload... the command is sent to the device, but the LED blinks red, meaning it didn't understand the command.

How can I fix this?

**Comment by nielsnl68** [comment]
I have upgrade my node modules. please check of your issue still exist.
