### ISSUE TITLE
i2c-read Input - Writes Data

### ISSUE THREAD

**Issue by meifi** [nielsnl68/node-red-contrib-i2c#9]
Hi, 

on my i2c bus, i've connected some PCF8574. The i2c-scan works perfektly, but when i configure a i2c-input all ports on the PCF8574 were change... so its dont read the data - its set / change / wirte the values on the PCF... 

So how can i read the current values from the device? Can someone help me or give me a example? 

Best regards from germany

**Comment by nielsnl68** [comment]
Hello from the Netherlands 
Can you try to use the new js version is submitted some days ago? And see of that fixes your issue.

I dont have a dcf8574 myself so i cant test it.

**Comment by meifi** [comment]
Sure, ofcourse. I'll try it in the evening and will give a response

**Comment by meifi** [comment]
Hi, 

i've updated my local 26-i2c.js and have the same issues. It's looks like the script don't execute a "i2cget" but rather execute a "i2cset" ... 

Also what do you mean with the msg.command field? I think, when i do a i2c read i dont need any command or? 

Best regards from germany

**Comment by nielsnl68** [comment]
I have upgrade my node modules. please check of your issue still exist.
